# Generated by Django 5.2.12 on 2026-09-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_projectmember"),
        ("workspaces", "0006_delete_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmember",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to="workspaces.workspacemember",
            ),
        ),
    ]
