# Generated by Django 5.2.12 on 2026-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_created_by_invitation_workspacemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemember",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
