# Generated by Django 5.2.12 on 2026-04-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_workspacemember_avatar_url_workspacemember_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="project_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="invitation",
            name="task_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
