# Generated by Django 5.2.12 on 2026-05-07 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_invitation_project_ids_invitation_task_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together={("workspace", "user")},
        ),
    ]
