# Generated by Django 5.2.12 on 2026-07-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_alter_workspacemember_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
