# Generated by Django 5.2.12 on 2026-07-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Member", "Member"),
                    ("Viewer", "Viewer"),
                ],
                default="Member",
                max_length=20,
            ),
        ),
    ]
