# Generated by Django 5.2.12 on 2026-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_invitation_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("viewer", "Viewer")],
                default="member",
                max_length=20,
            ),
        ),
    ]
