# Generated by Django 5.2.12 on 2026-04-13 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("workspaces", "0002_workspace_created_by_invitation_workspacemember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROJECT_CREATED", "Project Created"),
                            ("TASK_CREATED", "Task Created"),
                            ("TASK_UPDATED", "Task Updated"),
                            ("TASK_MOVED", "Task Moved"),
                            ("MEMBER_ADDED", "Member Added"),
                        ],
                        default="PROJECT_CREATED",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("message", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
