# Generated by Django 5.2.12 on 2026-04-14 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activity_user"),
        ("workspaces", "0002_workspace_created_by_invitation_workspacemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="workspaces.workspace",
            ),
        ),
    ]
