# Generated by Django 5.2.12 on 2026-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_activity_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="description",
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROJECT_CREATED", "Project Created"),
                    ("TASK_CREATED", "Task Created"),
                    ("TASK_UPDATED", "Task Updated"),
                    ("TASK_MOVED", "Task Moved"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                ],
                default="PROJECT_CREATED",
                max_length=50,
                null=True,
            ),
        ),
    ]
