# Generated by Django 5.2.12 on 2026-04-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkspaceMembership",
        ),
    ]
