# Generated by Django 5.2.12 on 2026-06-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_projectmember"),
        ("tasks", "0001_initial"),
        ("workspaces", "0005_alter_workspacemember_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("workspace", "project", "name")},
        ),
    ]
